# Generated by Django 3.1.7 on 2021-03-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
